"""
pack_assets.py
----------------
Turns every picture inside launcher_assets/ into a single file called
asset_data.py, with each picture stored as a block of plain text
(base64) instead of being a separate binary picture file.

Why: instead of a whole folder full of individual .png files, everything
lives in one readable Python file - easier to look at, back up, or send
to someone else as a single file.

HOW TO USE IT:
    Run this anytime after capturing/recapturing icons with
    capture_icons.py, to refresh asset_data.py with the latest pictures
    (from the repo root):

        python backend/pack_assets.py

The launcher automatically uses asset_data.py if it exists - you don't
need to change anything else. If you ever want to go back to plain
picture files instead, just delete asset_data.py.
"""

import base64
import os

import app_paths

ASSETS_DIR = app_paths.path("launcher_assets")
OUTPUT_FILE = app_paths.path("asset_data.py")


def main():
    if not os.path.isdir(ASSETS_DIR):
        print(f"No launcher_assets folder found at {ASSETS_DIR} - nothing to pack.")
        print("Run capture_icons.py first to capture some pictures.")
        return

    entries = []
    count = 0
    for filename in sorted(os.listdir(ASSETS_DIR)):
        if not filename.lower().endswith(".png"):
            continue
        key = filename[:-4]
        with open(os.path.join(ASSETS_DIR, filename), "rb") as f:
            encoded = base64.b64encode(f.read()).decode("ascii")
        entries.append(f'    "{key}": (\n        "{encoded}"\n    ),')
        count += 1

    if count == 0:
        print(f"No .png files found in {ASSETS_DIR} - nothing to pack.")
        return

    with open(OUTPUT_FILE, "w") as f:
        f.write('"""\n')
        f.write("asset_data.py\n")
        f.write("---------------\n")
        f.write("Auto-generated by pack_assets.py - do not edit by hand.\n")
        f.write("Every picture the launcher needs, stored as plain text (base64)\n")
        f.write("instead of separate picture files. Re-run pack_assets.py any time\n")
        f.write("you capture new/updated pictures to refresh this file.\n")
        f.write('"""\n\n')
        f.write("ASSETS = {\n")
        f.write("\n".join(entries))
        f.write("\n}\n")

    print(f"Packed {count} picture(s) into {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
