"""
pack_assets.py
----------------
Packs every picture in launcher_assets/ into one file, asset_data.py
(base64 text instead of separate .png files) - easier to back up or
send as a single file. The launcher uses asset_data.py automatically if
it exists; delete it to go back to plain picture files.

Usage: python backend/pack_assets.py
(run anytime after capturing/recapturing icons)
"""

import base64
import os

import app_paths

ASSETS_DIR = app_paths.path("launcher_assets")
OUTPUT_FILE = app_paths.path("asset_data.py")


def main():
    if not os.path.isdir(ASSETS_DIR):
        print(f"No launcher_assets folder found at {ASSETS_DIR} - nothing to pack.")
        print("Run capture_icons.py first to capture some pictures.")
        return

    entries = []
    count = 0
    for filename in sorted(os.listdir(ASSETS_DIR)):
        if not filename.lower().endswith(".png"):
            continue
        key = filename[:-4]
        with open(os.path.join(ASSETS_DIR, filename), "rb") as f:
            encoded = base64.b64encode(f.read()).decode("ascii")
        entries.append(f'    "{key}": (\n        "{encoded}"\n    ),')
        count += 1

    if count == 0:
        print(f"No .png files found in {ASSETS_DIR} - nothing to pack.")
        return

    with open(OUTPUT_FILE, "w") as f:
        f.write('"""\n')
        f.write("asset_data.py\n")
        f.write("---------------\n")
        f.write("Auto-generated by pack_assets.py - do not edit by hand.\n")
        f.write("Every launcher picture, stored as base64 text.\n")
        f.write('"""\n\n')
        f.write("ASSETS = {\n")
        f.write("\n".join(entries))
        f.write("\n}\n")

    print(f"Packed {count} picture(s) into {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
